### ISSUE TITLE
Issue/Polish checklist for migrated form to node

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/student-registration#39]
A few things that already needed correcting as well as some new issues appeared with the migration of the Webform to Node. This is a punchlist of those issues. Some may have individual tickets.

- [x] Implement the Region Select even without logic so form flow can be reviewed
- [x] Replace "Other" gender with "Decline to state" (or make it data driven by salesforce)
- [ ] Need to support "Other-- Write in" (2 fields) for Ethnicity. The writein field can't be blank.
- [x] Can't seem to select/enter anything in the Allergies field
- [ ] Drop Mailing Country
- [x] Make Second Emergency Contact "optional". e.g. a grey box around this section with OPTIONAL at the top
- [ ] Submit needs to really verify a contact was created or relay an error if there is one
- [x] Need to replicate the Waiver flow in its MVP form as seen in https://student-registration-stage.herokuapp.com/#

**Comment by CritiqalPete** [comment]
Closing this and creating tickets for the remaining items as "Quick-Fix" requests
